# Generated by Django 5.1.5 on 2025-02-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Project Manager'), ('MEMBER', 'Team Member')], default='MEMBER', max_length=10),
        ),
    ]
